### ISSUE TITLE
[Feature Request] Config changed event

### ISSUE THREAD

**Issue by MincraftEinstein** [fzzyhmstrs/fconfig#11]
Any chance you could add some kind of config changed event?

I have a couple of mods that are using Forge Config API Port and I want to switch to using this, but both mods require that I refresh some things, like repopulating a list or refreshing a cache when the config value is changed. Right now that would mean I would have to require the user to restart the game which I'd rather not do.

I'm not very good with kotlin, but if you're ok with it I could try to do it and make a PR when I'm done

**Comment by fzzyhmstrs** [comment]
This is a feature I am adding to the in dev 0.5.0. There will be an `onChangedClient` and `onChangedServer` that will fire once per respective side when the config state is "popped" (typically when the config changed are applied and/or the config screen is closed)

**Comment by MincraftEinstein** [comment]
Great! Thanks for letting me know
