### ISSUE TITLE
Float slider freeze

### ISSUE THREAD

**Issue by MincraftEinstein** [fzzyhmstrs/fconfig#16]
Float configs or double configs defined with a float, with a minimum value lower than 0.5 that use a slider cause the game to freeze when opening the containing screen.

Language: Java
Mod version: 5.0.1
Game version: 1.21.1
Mod Loader: Fabric and Forge

**Comment by fzzyhmstrs** [comment]
I'll look into it, thanks

**Comment by fzzyhmstrs** [comment]
can you send me the exact validation snippet that was causing the problem so I can try to replicate it on my end with the same input? thanks.

**Comment by fzzyhmstrs** [comment]
I believe I have a fix inDev, but it would still be nice to get the validation that caused the problem so I can directly check

**Comment by MincraftEinstein** [comment]
Sure. here

```
    public ValidatedFloat aFloat = new ValidatedFloat(1, 1, 0.3F);
    @ValidatedFloat.Restrict(min = 0.3F, max = 1)
    public float aFloat2 = 1;
    public ValidatedFloat aFloat3 = new ValidatedFloat(1, 1, 0.3F);
    public ValidatedDouble aDouble = new ValidatedDouble(1, 1, 0.3F);
```
Any of these will cause the issue

**Comment by fzzyhmstrs** [comment]
thank you. Confirmed fixed in dev. patch will be out soon
![image](https://github.com/user-attachments/assets/6f2716f8-b468-4f90-abf1-5febc6e5866b)
