### ISSUE TITLE
Version 5.4/5.5 not working on Neoforge 1.20.1

### ISSUE THREAD

**Issue by Sylthena** [fzzyhmstrs/fconfig#20]
Requires forge version 47.3 but no 1.20.1 version of Neoforge uses that version.

**Comment by fzzyhmstrs** [comment]
What is the latest version that 1.20.1 neoforge uses? They don't tell me on neoforged website, that I could easily find

**Comment by fzzyhmstrs** [comment]
If its stuck on an older version, I might have to break the 1.20.1 version apart, as 47.3 on forge proper has some breaking changes in networking per another issue I just closed that added the 47.3 check

**Comment by fzzyhmstrs** [comment]
I've taken a different approach, using a more version-agnostic approach that is available in the older version and the newer. Should be resolved as of the -fix1 patch. NOTE: An older version of forge wasn't behaving in dev to let me test it before upload.
