### ISSUE TITLE
Resetting enums to default

### ISSUE THREAD

**Issue by MincraftEinstein** [fzzyhmstrs/fconfig#21]
Resetting an enum config reverts to the first defined enum value rather than the value defined by the variable

```java
public TestEnum testConfig = TestEnum.VALUE_2;

public enum TestEnum {
    VALUE_1,
    VALUE_2
}
```
When the config is reset the restored value will be `VALUE_1` not the defined default `VALUE_2`

Minecraft version: 1.21
Mod version: 0.5.5
Mod loader: Neoforge and Fabric
Language: Java

**Comment by fzzyhmstrs** [comment]
fixed inDev for release 0.5.6
