### ISSUE TITLE
[Bug_Unexpected Crash]Index 1 out of bounds for length 1

### ISSUE THREAD

**Issue by OcrSu** [fzzyhmstrs/fconfig#24]
MC：1.21.1
NeoForge：21.1.83
Java：21 Oracle
OS：Windows10
ModVer：
~~~
fzzy_config-0.5.8+1.21+neoforge.jar
particle_core-0.2.5+1.21+neoforge.jar
SubtleEffects-neoforge-1.21-1.7.0.jar
~~~

This crash occurred when I started the game, but it was not 100% triggered.
Although it is a difficult to trigger crash, I still think it is appropriate to provide feedback to you.
If you can identify where the problem is and fix it, that's the best thing.
If you think this issue is bothering you, you can choose to close it.

Log:
https://gist.github.com/OcrSu/a7a332db9f752f5b35396a4be9490dd4

**Comment by fzzyhmstrs** [comment]
Hi, thank you for the report. I have made a fix for it to be released in 0.5.9. I have never experienced this problem on my end, so I'm not 100% certain the fix will work. Once 0.5.9 is out I will close this issue. If the error comes back, the issue can be re-opened then.
