### ISSUE TITLE
Cannot reference non-static method "ConfigApi.openScreen" or "ConfigApiJava.openScreen" from a static context in java

### ISSUE THREAD

**Issue by QiuShui1012** [fzzyhmstrs/fconfig#9]
Same as title. 
This method should also be annotated with @JvmStatic, otherwise it can only be called by instantiating this class in Java. 
![image](https://github.com/user-attachments/assets/b5c523a9-ea7a-4509-b077-8d67f565c1d8)
↓Need to be called by instantiation - but the constructor method is private.
![image](https://github.com/user-attachments/assets/1f6dbf1a-551b-428a-9bc1-95ecaa0da68b)

**Comment by fzzyhmstrs** [comment]
Just use ConfigApi.INSTANCE, automatically provided for you. Unfortunately adding JvmStatic would be a breaking API change at this point.

**Comment by QiuShui1012** [comment]
> Just use ConfigApi.INSTANCE, automatically provided for you. Unfortunately adding JvmStatic would be a breaking API change at this point.

Understood. thank!
